---
# check docker and docker-compose installation
- name: Check and install Docker and Docker Compose if not installed
  hosts: cloud1
  become: true
  become_method: sudo
  vars_files:
    - secrets.yaml

  tasks:
    - name: Check Docker installation
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      no_log: true

    - name: Check Docker Compose installation
      command: docker compose version
      register: docker_compose_installed
      ignore_errors: yes
      no_log: true

    - name: Check Makefile installation
      command: make --version
      register: make_installed
      ignore_errors: yes
      no_log: true

    - name: Display Docker check result
      debug:
        msg: >-
          {% if docker_installed.rc == 0 %}
            ✅ Docker is installed.
          {% else %}
            ❌ Docker is not installed.
          {% endif %}

    - name: Display Docker Compose check result
      debug:
        msg: >-
          {% if docker_compose_installed.rc == 0 %}
            ✅ Docker Compose is installed.
          {% else %}
            ❌ Docker Compose is not installed.
          {% endif %}

    - name: Display Makefile check result
      debug:
        msg: >-
          {% if make_installed.rc == 0 %}
            ✅ Makefile is installed.
          {% else %}
            ❌ Makefile is not installed.
          {% endif %}

    - name: Update APT cache
      apt:
        update_cache: yes
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg-agent
        state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      when: docker_installed.rc != 0

    - name: Ensure docker CLI plugin directory exists
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'
      when: docker_compose_installed.rc != 0

    - name: Download latest Docker Compose binary
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
      when: docker_compose_installed.rc != 0

    - name: Install make
      apt:
        name:
          - make
        state: latest
      when: make_installed.rc != 0
    
    - name: Add user to docker group
      user:
        name: tariq
        groups: docker
        append: yes
      when: docker_installed.rc != 0
    
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true
      when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

