---
- name: Clean up deployment
  hosts: localhost
  become: true
  become_user: "{{ ansible_become_user }}"
  vars_files:
    - secrets.yaml

  vars:
    cleanup_target: "clean"  # Change to 'fclean' to do a full cleanup

  tasks:
    - name: Run Makefile with selected target
      make:
        chdir: '/home/tariq/Desktop/cloud-1-deploy-dir/app'
        target: "{{ cleanup_target }}"

# To call f clean use the follow cammand
# ansible-playbook clean-app-deployment-playbook.yaml -e "cleanup_target=fclean"

