---
- name: Deploy application locally
  hosts: localhost
  become: true
  become_user: "{{ ansible_become_user }}" 
  vars_files:
    - secrets.yaml
  tasks:
    - name: Check if the repository is already cloned
      stat:
        path: '/home/tariq/Desktop/cloud-1-deploy-dir/.git'
      register: repo_status

    - name: Clone the repository if it does not exist
      git:
        repo: 'https://github.com/tariqelb/cloud-1.git'
        dest: '/home/tariq/Desktop/cloud-1-deploy-dir'
        version: 'master'
      when: repo_status.stat.exists == False

    - name: Pull latest changes if repository is already cloned
      git:
        repo: 'https://github.com/tariqelb/cloud-1.git'
        dest: '/home/tariq/Desktop/cloud-1-deploy-dir'
        version: 'master'
        update: yes
      when: repo_status.stat.exists == True

    - name: Run Makefile to deploy the app
      make:
        chdir: '/home/tariq/Desktop/cloud-1-deploy-dir/app'
        target: all
 
