# check health of docker containers
---
- name: Check containers state
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check if nginx container exists
      community.docker.docker_container_info:
        name: nginx
      register: nginx_info
      failed_when: false  # Don't fail if container is missing

    - name: Show container status
      debug:
        msg: >-
          {% if nginx_info.container is none %}
            ❌ nginx container does not exist.
          {% elif nginx_info.container.State.Running %}
            ✅ nginx container is running.
          {% else %}
            ⚠️ nginx container exists but is NOT running.
          {% endif %}

